[project]
name = "etl-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.12.0",
    "jsonschema>=4.25.1",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "requests>=2.32.5",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "PERF", "UP"] 
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ty]
